---
- name: Ensure nullmailer is installed
  apt: name=nullmailer state=installed

- name: Set nullmailer's mailname
  copy: dest='{{item.0}}' content='{{item.1}}'
        owner=root group=mail mode=0644
  with_lists:
  # used as host-part for addresses:
  - [ '/etc/mailname', '{{nullmailer_mailname}}']
  # used for generating the message-ids:
  - [ '/etc/nullmailer/idhost', '{{nullmailer_idhost}}']
  notify: Reload nullmailer

- name: Ensure no conflicting configs exit
  file: state=absent name='{{item}}'
  with_items:
   - /etc/nullmailer/me
   # domain name appended to allif address is does not contain a dot
   - /etc/nullmailer/defaultdomain
   # hostname is sender-addresses is missing host-part
   - /etc/nullmailer/defaulthost
  notify: Reload nullmailer

- name: Set configs for nullmailer
  copy: dest='/etc/nullmailer/{{item.0}}' content='{{item.1}}'
        owner=root group=mail mode=0644
  with_lists:
  - [ 'adminaddr', '{{nullmailer_adminaddr}}']
  - [ 'helohost', '{{nullmailer_helohost}}']
  - [ 'pausetime', '{{nullmailer_pausetime}}']
  - [ 'sendtimeout', '{{nullmailer_sendtimeout}}']
  when: item.1
  notify: Reload nullmailer

- name: Unset configs for nullmailer
  file: name='/etc/nullmailer/{{item.0}}' state=absent
  with_lists:
  - [ 'adminaddr', '{{nullmailer_adminaddr}}']
  - [ 'helohost', '{{nullmailer_helohost}}']
  - [ 'pausetime', '{{nullmailer_pausetime}}']
  - [ 'sendtimeout', '{{nullmailer_sendtimeout}}']
  when: not item.1
  notify: Reload nullmailer

- name: "Set nullmailer's remotes"
  copy: dest='/etc/nullmailer/remotes'
        content='{{nullmailer_remotes | join("\n") }}'
        owner=root group=mail mode=0640
  notify: Reload nullmailer

- name: Start nullmailer
  service: name=nullmailer state=started enabled=True


# Setup a simple smtpd via xinet

- name: Ensure xinetd is installed
  apt: name=xinetd state=installed
  when: nullmailer_smtpd

- name: Configure xinetd for nullmailer
  template: src=nullmailer-smtpd.j2
            dest=/etc/xinetd.d/nullmailer-smtpd
            owner=root group=root mode=0644
  notify: Reload xinetd
  when: nullmailer_smtpd

- name: Remove configuration of xinetd for nullmailer if nullmailer is disabled
  file: path=/etc/xinetd.d/nullmailer-smtpd
        state=absent
  notify: Reload xinetd
  when: not nullmailer_smtpd

- name: Start xinetd
  service: name=xinetd state=started enabled=True
  when: nullmailer_smtpd
